# Generated by Django 5.2.7 on 2026-03-30 07:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('age_group', models.IntegerField(choices=[(1, '18–20'), (2, '21–23'), (3, '24–26'), (4, '27+')])),
                ('study_year', models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')])),
                ('university_type', models.IntegerField(choices=[(1, 'Public'), (2, 'Private'), (3, 'Other'), (4, 'Prefer not to say')])),
                ('living_place', models.IntegerField(choices=[(1, 'With family'), (2, 'Hall/Hostel'), (3, 'Mess'), (4, 'Alone')])),
                ('sleep_hours', models.IntegerField(choices=[(1, 'Less than 5'), (2, '5–6'), (3, '7–8'), (4, '8+')])),
                ('device_usage', models.IntegerField(choices=[(1, '<2h'), (2, '2–4h'), (3, '4–6h'), (4, '6h+')])),
                ('breakfast', models.IntegerField(choices=[(1, 'Regular'), (2, 'Sometimes skip'), (3, 'Often skip'), (4, 'Very irregular')])),
                ('addiction', models.IntegerField(choices=[(1, 'Smoking'), (2, 'Gaming'), (3, 'Caffeine'), (4, 'None')])),
                ('interest', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half'), (3, 'Nearly every day')])),
                ('anxiety', models.IntegerField(choices=[(0, 'Not at all'), (1, 'Several days'), (2, 'More than half'), (3, 'Nearly every day')])),
                ('social_feeling', models.IntegerField(choices=[(1, 'Supported'), (2, 'Anxious'), (3, 'Neutral'), (4, 'Irritated')])),
                ('self_rating', models.IntegerField(choices=[(2, '1–3'), (5, '4–6'), (8, '7–8'), (10, '9–10')])),
                ('ai_usage', models.IntegerField(choices=[(1, 'Yes'), (2, 'Maybe'), (3, 'No'), (4, 'Not sure')])),
                ('ai_action', models.IntegerField(choices=[(1, 'Tips'), (2, 'Talk to friend'), (3, 'Counsellor'), (4, 'Do nothing')])),
                ('risk_level', models.CharField(max_length=10, null=True)),
                ('score', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
